name: (PR -> 'develop') Test CI
on:
  pull_request:
    branches:
      - "develop"
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: "3.11"
      POETRY: "1.7.1"
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
    - name: Checkout Branch
      uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ env.PYTHON }}
    - name: Setup Poetry
      uses: abatilo/actions-poetry@v3
      with:
        poetry-version: ${{ env.POETRY }}
    - name: Install Dependencies
      run: poetry install --with ci
    - name: Generate coverage report
      run: poetry run pytest
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ env.CODECOV_TOKEN }}
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./coverage.xml,./coverage1.xml,./coverage2.xml,!./cache
        flags: unittests
        name: codecov-umbrella
        verbose: true
